// import { DishType } from '@shared-types';

// export const DISHES: DishType[] = [
//     // Напитки
//     {
//         id: 1,
//         name: 'Капучино',
//         imageRef: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800',
//         type: 'drinks',
//         energy: {
//             kcal: 120,
//             protein: 6,
//             fat: 6,
//             carbs: 10,
//         },
//         price: 180,
//         description: 'Классический итальянский кофе с нежной молочной пенкой',
//     },
//     {
//         id: 2,
//         name: 'Свежевыжатый апельсиновый сок',
//         imageRef: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800',
//         type: 'drinks',
//         energy: {
//             kcal: 110,
//             protein: 2,
//             fat: 0,
//             carbs: 26,
//         },
//         price: 220,
//         description: 'Натуральный сок из свежих апельсинов без добавления сахара',
//     },
//     {
//         id: 3,
//         name: 'Зеленый чай с жасмином',
//         imageRef: 'https://thumbs.dreamstime.com/b/tea-jasmine-flowers-glass-teapot-tea-jasmine-flowers-glass-teapot-table-117944963.jpg',
//         type: 'drinks',
//         energy: {
//             kcal: 5,
//             protein: 0,
//             fat: 0,
//             carbs: 1,
//         },
//         price: 150,
//         description: 'Ароматный китайский чай с цветками жасмина',
//     },
//     {
//         id: 4,
//         name: 'Лимонад домашний',
//         imageRef: 'https://www.koolinar.ru/all_image/article/3/3187/article-321dcaa7-1884-457b-9620-8783451e814d_large.jpg',
//         type: 'drinks',
//         energy: {
//             kcal: 85,
//             protein: 0,
//             fat: 0,
//             carbs: 22,
//         },
//         price: 190,
//         description: 'Освежающий лимонад из свежих лимонов с мятой',
//     },

//     // Закуски
//     {
//         id: 5,
//         name: 'Брускетта с томатами',
//         imageRef: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
//         type: 'appetizers',
//         energy: {
//             kcal: 180,
//             protein: 6,
//             fat: 8,
//             carbs: 22,
//         },
//         price: 280,
//         description: 'Хрустящие тосты с сочными томатами, базиликом и оливковым маслом',
//     },
//     {
//         id: 6,
//         name: 'Сырная тарелка',
//         imageRef: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800',
//         type: 'appetizers',
//         energy: {
//             kcal: 420,
//             protein: 24,
//             fat: 35,
//             carbs: 5,
//         },
//         price: 650,
//         description: 'Ассорти из благородных сыров с виноградом и орехами',
//     },
//     {
//         id: 7,
//         name: 'Креветки в кляре',
//         imageRef: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800',
//         type: 'appetizers',
//         energy: {
//             kcal: 320,
//             protein: 18,
//             fat: 16,
//             carbs: 28,
//         },
//         price: 580,
//         description: 'Хрустящие креветки в легком кляре с соусом тартар',
//     },

//     // Салаты
//     {
//         id: 8,
//         name: 'Цезарь с курицей',
//         imageRef: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
//         type: 'salads',
//         energy: {
//             kcal: 350,
//             protein: 28,
//             fat: 22,
//             carbs: 18,
//         },
//         price: 420,
//         description: 'Классический салат с курицей, листьями романо, пармезаном и соусом цезарь',
//     },
//     {
//         id: 9,
//         name: 'Греческий салат',
//         imageRef: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
//         type: 'salads',
//         energy: {
//             kcal: 280,
//             protein: 8,
//             fat: 22,
//             carbs: 12,
//         },
//         price: 380,
//         description: 'Свежие овощи с сыром фета, маслинами и оливковым маслом',
//     },
//     {
//         id: 10,
//         name: 'Салат с лососем и авокадо',
//         imageRef: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
//         type: 'salads',
//         energy: {
//             kcal: 390,
//             protein: 22,
//             fat: 28,
//             carbs: 14,
//         },
//         price: 550,
//         description: 'Нежный лосось с авокадо, микс салатов и цитрусовой заправкой',
//     },

//     // Горячее
//     {
//         id: 11,
//         name: 'Стейк рибай',
//         imageRef: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
//         type: 'hot',
//         energy: {
//             kcal: 680,
//             protein: 52,
//             fat: 48,
//             carbs: 4,
//         },
//         price: 1250,
//         description: 'Сочный мраморный стейк рибай средней прожарки с овощами гриль',
//     },
//     {
//         id: 12,
//         name: 'Лосось на гриле',
//         imageRef: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=800',
//         type: 'hot',
//         energy: {
//             kcal: 420,
//             protein: 38,
//             fat: 26,
//             carbs: 8,
//         },
//         price: 780,
//         description: 'Филе лосося на гриле с лимонным маслом и спаржей',
//     },
//     {
//         id: 13,
//         name: 'Ризотто с белыми грибами',
//         imageRef: 'https://images.news.ru/2025/08/11/66wLiMLHXQKyAygEKkYd4hbEkTs7gUajJGOW9rqx_780.png',
//         type: 'hot',
//         energy: {
//             kcal: 480,
//             protein: 14,
//             fat: 18,
//             carbs: 62,
//         },
//         price: 520,
//         description: 'Кремовое ризотто с белыми грибами и пармезаном',
//     },
//     {
//         id: 14,
//         name: 'Утиная грудка с апельсиновым соусом',
//         imageRef: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
//         type: 'hot',
//         energy: {
//             kcal: 540,
//             protein: 42,
//             fat: 32,
//             carbs: 18,
//         },
//         price: 850,
//         description: 'Томленая утиная грудка с карамелизированным апельсиновым соусом',
//     },

//     // Выпечка
//     {
//         id: 15,
//         name: 'Круассан классический',
//         imageRef: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 280,
//             protein: 6,
//             fat: 16,
//             carbs: 28,
//         },
//         price: 150,
//         description: 'Хрустящий французский круассан из слоеного теста',
//     },
//     {
//         id: 16,
//         name: 'Чиабатта с маслинами',
//         imageRef: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 240,
//             protein: 8,
//             fat: 6,
//             carbs: 38,
//         },
//         price: 180,
//         description: 'Итальянский хлеб чиабатта с маслинами и травами',
//     },
//     {
//         id: 17,
//         name: 'Синнабон',
//         imageRef: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 420,
//             protein: 7,
//             fat: 18,
//             carbs: 58,
//         },
//         price: 220,
//         description: 'Ароматная булочка с корицей и сливочной глазурью',
//     },
//     {
//         id: 18,
//         name: 'Эклер шоколадный',
//         imageRef: 'https://d5ln38p3754yc.cloudfront.net/conference_facebook_images/9744171/original/1716906631-ce07c9e649c846d2.jpg?1716906631',
//         type: 'bakery',
//         energy: {
//             kcal: 350,
//             protein: 6,
//             fat: 20,
//             carbs: 38,
//         },
//         price: 180,
//         description: 'Воздушное заварное пирожное с шоколадным кремом и глазурью',
//     },
//     {
//         id: 19,
//         name: 'Штрудель яблочный',
//         imageRef: 'https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 290,
//             protein: 5,
//             fat: 12,
//             carbs: 42,
//         },
//         price: 200,
//         description: 'Традиционный австрийский десерт с яблоками и корицей',
//     },

//     // Десерты
//     {
//         id: 20,
//         name: 'Тирамису',
//         imageRef: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 450,
//             protein: 10,
//             fat: 28,
//             carbs: 42,
//         },
//         price: 350,
//         description: 'Классический итальянский десерт с маскарпоне и савоярди',
//     },
//     {
//         id: 21,
//         name: 'Чизкейк Нью-Йорк',
//         imageRef: 'https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 380,
//             protein: 8,
//             fat: 24,
//             carbs: 34,
//         },
//         price: 320,
//         description: 'Нежный сливочный чизкейк на песочной основе',
//     },
//     {
//         id: 22,
//         name: 'Шоколадный фондан',
//         imageRef: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 410,
//             protein: 6,
//             fat: 22,
//             carbs: 48,
//         },
//         price: 380,
//         description: 'Горячий шоколадный кекс с жидкой начинкой и ванильным мороженым',
//     },
//     {
//         id: 23,
//         name: 'Панна котта с ягодами',
//         imageRef: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
//         type: 'bakery',
//         energy: {
//             kcal: 290,
//             protein: 5,
//             fat: 18,
//             carbs: 26,
//         },
//         price: 280,
//         description: 'Нежный итальянский десерт из сливок с ягодным соусом',
//     },

//     // Бар
//     {
//         id: 24,
//         name: 'Мохито классический',
//         imageRef: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800',
//         type: 'bar',
//         energy: {
//             kcal: 180,
//             protein: 0,
//             fat: 0,
//             carbs: 24,
//         },
//         price: 420,
//         description: 'Освежающий коктейль с ромом, мятой, лаймом и содовой',
//     },
//     {
//         id: 25,
//         name: 'Апероль Шприц',
//         imageRef: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800',
//         type: 'bar',
//         energy: {
//             kcal: 150,
//             protein: 0,
//             fat: 0,
//             carbs: 18,
//         },
//         price: 480,
//         description: 'Итальянский аперитив с аперолем, просекко и содовой',
//     },
//     {
//         id: 26,
//         name: 'Олд Фэшн',
//         imageRef: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
//         type: 'bar',
//         energy: {
//             kcal: 160,
//             protein: 0,
//             fat: 0,
//             carbs: 8,
//         },
//         price: 550,
//         description: 'Классический виски-коктейль с биттером и сахаром',
//     },
//     {
//         id: 27,
//         name: 'Эспрессо Мартини',
//         imageRef: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
//         type: 'bar',
//         energy: {
//             kcal: 220,
//             protein: 1,
//             fat: 0,
//             carbs: 18,
//         },
//         price: 490,
//         description: 'Бодрящий коктейль с водкой, кофейным ликером и эспрессо',
//     },
// ];
