import { Dish } from '@/ui/menu-itemUI/MenuItemUI';
import transparentCros from '@/assets/svg/croissant.svg';
import borsch from '@/assets/images/dishes/borsch.png';

export type DishWithCategory = Dish;

export const DISHES: DishWithCategory[] = [
    {
        id: 1,
        name: 'Паста арабьята',
        imageRef: transparentCros,
        type: 'pasta',
        energy: {
            kcal: 0,
            protein: 0,
            fat: 0,
            carbs: 0,
        },
        price: 450,
        description: 'Традиционная итальянская паста с острой томатной подливкой и чесноком',
    },
    {
        id: 2,
        name: 'Рамен',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Beef_ramen_-_Sun_Noodle%2C_Kailua%2C_Oahu.jpg',
        type: 'soups',
        energy: {
            kcal: 450,
            protein: 20,
            fat: 15,
            carbs: 60,
        },
        price: 380,
        description: 'Японский суп с пшеничной лапшой, бульоном и различными добавками',
    },
    {
        id: 3,
        name: 'Борщ',
        imageRef: borsch,
        type: 'soups',
        energy: {
            kcal: 150,
            protein: 8,
            fat: 5,
            carbs: 20,
        },
        price: 280,
        description: 'Традиционный украинский суп с капустой, свеклой и мясом',
    },
    {
        id: 4,
        name: 'Цезарь',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Caesar_salad_%281%29.jpg/1280px-Caesar_salad_%281%29.jpg',
        type: 'dinner',
        energy: {
            kcal: 350,
            protein: 12,
            fat: 25,
            carbs: 20,
        },
        price: 420,
        description: 'Классический салат с курицей, листьями салата, сыром пармезан и соусом цезарь',
    },
    {
        id: 5,
        name: 'Пицца Маргарита',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/1280px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        type: 'dinner',
        energy: {
            kcal: 800,
            protein: 30,
            fat: 25,
            carbs: 120,
        },
        price: 550,
        description: 'Классическая итальянская пицца с томатным соусом, моцареллой и базиликом',
    },
    {
        id: 6,
        name: 'Стейк',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Beef_fillet_steak_with_mushroom_sauce.jpg/1280px-Beef_fillet_steak_with_mushroom_sauce.jpg',
        type: 'dinner',
        energy: {
            kcal: 600,
            protein: 45,
            fat: 45,
            carbs: 2,
        },
        price: 850,
        description: 'Сочный говяжий стейк, приготовленный на гриле с овощами',
    },
    {
        id: 7,
        name: 'Бургер',
        imageRef: 'https://w7.pngwing.com/pngs/487/480/png-transparent-hamburger-fast-food-french-fries-hamburger-junk-food-mcdonald-s-big-mac-junk-food-fast-food-french-fries-hamburger.png',
        type: 'dinner',
        energy: {
            kcal: 750,
            protein: 35,
            fat: 40,
            carbs: 55,
        },
        price: 480,
        description: 'Сочный бургер с говяжьей котлетой, сыром, овощами и соусом',
    },
    {
        id: 8,
        name: 'Тирамису',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Tiramisu_with_blueberries_and_raspberries%2C_July_2011.jpg/1280px-Tiramisu_with_blueberries_and_raspberries%2C_July_2011.jpg',
        type: 'deserts',
        energy: {
            kcal: 450,
            protein: 10,
            fat: 25,
            carbs: 45,
        },
        price: 320,
        description: 'Классический итальянский десерт на основе маскарпоне и печенья савоярди',
    },
    {
        id: 9,
        name: 'Панна Котта',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Panna_cotta_ai_frutti_di_bosco.JPG/1280px-Panna_cotta_ai_frutti_di_bosco.JPG',
        type: 'deserts',
        energy: {
            kcal: 320,
            protein: 6,
            fat: 25,
            carbs: 22,
        },
        price: 280,
        description: 'Нежный итальянский десерт на основе сливок с ягодным соусом',
    },
    {
        id: 10,
        name: 'Сырники',
        imageRef: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Syrniki_white_bg.jpg/1280px-Syrniki_white_bg.jpg',
        type: 'breakfast',
        energy: {
            kcal: 280,
            protein: 18,
            fat: 12,
            carbs: 25,
        },
        price: 220,
        description: 'Традиционное русское блюдо из творога с добавлением муки и яиц',
    },
];
