import { Dish } from '@/shared/ui/menu-itemUI/MenuItemUI';
import burgerSVG from '@/assets/svg/burger.svg';

// export type DishWithCategory = Dish;

export const DISHES: Dish[] = [
    {
        id: 1,
        name: 'Паста арабьята',
        imageRef: burgerSVG,
        type: 'pasta',
        energy: {
            kcal: 0,
            protein: 0,
            fat: 0,
            carbs: 0,
        },
        price: 450,
        description: 'Традиционная итальянская паста с острой томатной подливкой и чесноком',
    },
    {
        id: 2,
        name: 'Рамен',
        imageRef: burgerSVG,
        type: 'soups',
        energy: {
            kcal: 450,
            protein: 20,
            fat: 15,
            carbs: 60,
        },
        price: 380,
        description: 'Японский суп с пшеничной лапшой, бульоном и различными добавками',
    },
    {
        id: 3,
        name: 'Борщ',
        imageRef: burgerSVG,
        type: 'soups',
        energy: {
            kcal: 150,
            protein: 8,
            fat: 5,
            carbs: 20,
        },
        price: 280,
        description: 'Традиционный украинский суп с капустой, свеклой и мясом',
    },
    {
        id: 4,
        name: 'Цезарь',
        imageRef: burgerSVG,
        type: 'dinner',
        energy: {
            kcal: 350,
            protein: 12,
            fat: 25,
            carbs: 20,
        },
        price: 420,
        description: 'Классический салат с курицей, листьями салата, сыром пармезан и соусом цезарь',
    },
    {
        id: 5,
        name: 'Пицца Маргарита',
        imageRef: burgerSVG,
        type: 'dinner',
        energy: {
            kcal: 800,
            protein: 30,
            fat: 25,
            carbs: 120,
        },
        price: 550,
        description: 'Классическая итальянская пицца с томатным соусом, моцареллой и базиликом',
    },
    {
        id: 6,
        name: 'Стейк',
        imageRef: burgerSVG,
        type: 'dinner',
        energy: {
            kcal: 600,
            protein: 45,
            fat: 45,
            carbs: 2,
        },
        price: 850,
        description: 'Сочный говяжий стейк, приготовленный на гриле с овощами',
    },
    {
        id: 7,
        name: 'Бургер',
        imageRef: burgerSVG,
        type: 'dinner',
        energy: {
            kcal: 750,
            protein: 35,
            fat: 40,
            carbs: 55,
        },
        price: 480,
        description: 'Сочный бургер с говяжьей котлетой, сыром, овощами и соусом',
    },
    {
        id: 8,
        name: 'Тирамису',
        imageRef: burgerSVG,
        type: 'deserts',
        energy: {
            kcal: 450,
            protein: 10,
            fat: 25,
            carbs: 45,
        },
        price: 320,
        description: 'Классический итальянский десерт на основе маскарпоне и печенья савоярди',
    },
    {
        id: 9,
        name: 'Панна Котта',
        imageRef: burgerSVG,
        type: 'deserts',
        energy: {
            kcal: 320,
            protein: 6,
            fat: 25,
            carbs: 22,
        },
        price: 280,
        description: 'Нежный итальянский десерт на основе сливок с ягодным соусом',
    },
    {
        id: 10,
        name: 'Сырники',
        imageRef: burgerSVG,
        type: 'breakfast',
        energy: {
            kcal: 280,
            protein: 18,
            fat: 12,
            carbs: 25,
        },
        price: 220,
        description: 'Традиционное русское блюдо из творога с добавлением муки и яиц',
    },
];
